### ISSUE TITLE
problem with searching index

### ISSUE THREAD

**Issue by EmelyanovMax** [mariocoski/laravel-blogger#239]
As I reset index I got "There was a problem with reseting your searching index".
Also I have an error as I create new article

**Comment by EmelyanovMax** [comment]
The problem in your elastic search. This error mean the site does not see elastic search or has not permission to create new index. 
If you use Docker, you need edit config "config/scout.php" 
change parameter "hosts" from 'localhost' to name of docker-container, 'elasticsearch' as default.

**Comment by mariocoski** [comment]
Thank you very much for pointing that out
