### ISSUE TITLE
Description field in Articles is not active

### ISSUE THREAD

**Issue by EmelyanovMax** [mariocoski/laravel-blogger#240]
When I'm creating new Article, the field 'description' is not active. I click on, but there is no action and I can't to type. 
If I click on some special button, f.e. 'smiles' and choose one, I can type my description text.
If I edit Article there is no problem with it.

There is problem only with one field and only on one page.
I use docker containers with php 7.0, Ubuntu 14

**Comment by mariocoski** [comment]
Hi, sorry for late reply. Do you still have problem with description field?

**Comment by EmelyanovMax** [comment]
Thanks for letter, the problem is decided. 
Now I have no error.
