### ISSUE TITLE
blogger install error

### ISSUE THREAD

**Issue by goldensnow890219** [mariocoski/laravel-blogger#242]
Hi
I am trying to install blogger on my localhost.
(php artisan blogger:install)
I choose email, password, first and last name. then it has an error like this in next step. 

[ErrorException]
Trying to get property of non-object

I would like you help me how I can fix this issue.

sorry, I am so urgent now, so I would like you give me quick response.
thanks

**Comment by dinesh0666** [comment]
count(): Parameter must be an array or an object that implements Countable

**Comment by mariocoski** [comment]
try this: https://stackoverflow.com/questions/48343557/count-parameter-must-be-an-array-or-an-object-that-implements-countable

**Comment by icecreamsandwich** [comment]
> try this: https://stackoverflow.com/questions/48343557/count-parameter-must-be-an-array-or-an-object-that-implements-countable

That worked ,thanks

**Comment by icecreamsandwich** [comment]
By default, there is no category or articles available. And I couldn't create any categories from the dashboard. Is it the default behavior? Any way to dump some data? 

![image](https://user-images.githubusercontent.com/3961511/52691919-5767f800-2f88-11e9-9bff-e3fca9f353f1.png)

**Comment by mariocoski** [comment]
Basically, when you installed your blog, did you seeded database after migrating it? The seeds should contains one dummy category? php artisan db:seed?

**Comment by icecreamsandwich** [comment]
@mariocoski oops didn't seed it. thank you 
![image](https://user-images.githubusercontent.com/3961511/52738432-aa779480-2ff4-11e9-9846-b6aaf018f876.png)
