### ISSUE TITLE
  [Illuminate\Database\QueryException]   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.roles' doesn't exist (SQL: select * from `roles` where `name` = admin l   imit 1)

### ISSUE THREAD

**Issue by ekordev** [mariocoski/laravel-blogger#244]
and also:
```
  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.roles' doesn't exist

```

**Comment by mariocoski** [comment]
have you migrated db correctly?

**Comment by icecreamsandwich** [comment]
Truncate all the tables from the database and re-run the `php artisan migrate` once again to create all the migrations

**Comment by ekordev** [comment]
My apologies I was called out of town and wasn't able to respond. I will be
back at my work environment today and will check your suggestions and will
let you know thanks!
